# Sidebar navigation

- label: "Dylan Harrrrr"
  link: "/"
- label: "Getting started"
  link: "/getting-started"
- label: Usage
  items:
    - label: "Sqwak"
      link: "/sqwak"
    - label: "Navigation"
      link: "/usage/navigation"
    - label: "Customizing"
      link: "/usage/customizing"
    - label: "Using YAML files"
      link: "/usage/using-yaml-files"
    - label: "Remark Plugins"
      link: "/usage/remark-plugins"
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: "Github"
      link: https://github.com/jpedroschmitz/rocketdocs
